openapi: 3.0.0
info:
  title: Student Course API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/students:
    get:
      summary: Get all students
      responses:
        '200':
          description: A list of students
    post:
      summary: Create a new student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student created
  /api/students/{id}:
    get:
      summary: Get a student by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Student found
    put:
      summary: Update student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated
    delete:
      summary: Delete a student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
components:
  schemas:
    Student:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
